// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vet.DAL;

#nullable disable

namespace Vet.DAL.Migrations
{
    [DbContext(typeof(VetContext))]
    [Migration("20240419061104_ImagenesUsuario")]
    partial class ImagenesUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vet.DAL.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Imagen2")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UltimaFechaConexion")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Vet.DAL.Cita", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCita"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuenoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EstadoCita")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdMascota")
                        .HasColumnType("int");

                    b.Property<string>("VeterinarioPrincipalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VeterinarioSecundarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdCita");

                    b.HasIndex("DuenoId");

                    b.HasIndex("IdMascota");

                    b.HasIndex("VeterinarioPrincipalId");

                    b.HasIndex("VeterinarioSecundarioId");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("Vet.DAL.CitaMedicamento", b =>
                {
                    b.Property<int>("IdCitaMedicamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCitaMedicamento"));

                    b.Property<string>("Dosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCita")
                        .HasColumnType("int");

                    b.Property<int>("IdMedicamento")
                        .HasColumnType("int");

                    b.HasKey("IdCitaMedicamento");

                    b.HasIndex("IdCita");

                    b.HasIndex("IdMedicamento");

                    b.ToTable("CitaMedicamentos");
                });

            modelBuilder.Entity("Vet.DAL.Mascota", b =>
                {
                    b.Property<int>("IdMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMascota"));

                    b.Property<string>("DuenoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdRazaMascota")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoMascota")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Imagen2")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacionId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdMascota");

                    b.HasIndex("DuenoId");

                    b.HasIndex("IdRazaMascota");

                    b.HasIndex("UsuarioCreacionId");

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("Vet.DAL.Medicamento", b =>
                {
                    b.Property<int>("IdMedicamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedicamento"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadMedida")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMedicamento");

                    b.ToTable("Medicamentos");
                });

            modelBuilder.Entity("Vet.DAL.Padecimiento", b =>
                {
                    b.Property<int>("IdPadecimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPadecimiento"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPadecimiento");

                    b.ToTable("Padecimientos");
                });

            modelBuilder.Entity("Vet.DAL.PadecimientoMascota", b =>
                {
                    b.Property<int>("IdPadecimientoMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPadecimientoMascota"));

                    b.Property<int>("IdMascota")
                        .HasColumnType("int");

                    b.Property<int>("IdPadecimiento")
                        .HasColumnType("int");

                    b.HasKey("IdPadecimientoMascota");

                    b.HasIndex("IdMascota");

                    b.HasIndex("IdPadecimiento");

                    b.ToTable("PadecimientoMascotas");
                });

            modelBuilder.Entity("Vet.DAL.RazaMascota", b =>
                {
                    b.Property<int>("IdRazaMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRazaMascota"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("IdTipoMascota")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRazaMascota");

                    b.HasIndex("IdTipoMascota");

                    b.ToTable("RazaMascotas");
                });

            modelBuilder.Entity("Vet.DAL.TipoMascota", b =>
                {
                    b.Property<int>("IdTipoMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoMascota"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoMascota");

                    b.ToTable("TipoMascotas");
                });

            modelBuilder.Entity("Vet.DAL.Vacuna", b =>
                {
                    b.Property<int>("IdVacuna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVacuna"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Producto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoVacuna")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVacuna");

                    b.ToTable("Vacunas");
                });

            modelBuilder.Entity("Vet.DAL.VacunaMascota", b =>
                {
                    b.Property<int>("IdVacunaMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVacunaMascota"));

                    b.Property<DateTime>("FechaVacuna")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdMascota")
                        .HasColumnType("int");

                    b.Property<int>("IdVacuna")
                        .HasColumnType("int");

                    b.HasKey("IdVacunaMascota");

                    b.HasIndex("IdMascota");

                    b.HasIndex("IdVacuna");

                    b.ToTable("VacunaMascotas");
                });

            modelBuilder.Entity("Vet.DAL.Cita", b =>
                {
                    b.HasOne("Vet.DAL.ApplicationUser", "Dueno")
                        .WithMany()
                        .HasForeignKey("DuenoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vet.DAL.Mascota", "Mascota")
                        .WithMany("Citas")
                        .HasForeignKey("IdMascota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vet.DAL.ApplicationUser", "VeterinarioPrincipal")
                        .WithMany()
                        .HasForeignKey("VeterinarioPrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vet.DAL.ApplicationUser", "VeterinarioSecundario")
                        .WithMany()
                        .HasForeignKey("VeterinarioSecundarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dueno");

                    b.Navigation("Mascota");

                    b.Navigation("VeterinarioPrincipal");

                    b.Navigation("VeterinarioSecundario");
                });

            modelBuilder.Entity("Vet.DAL.CitaMedicamento", b =>
                {
                    b.HasOne("Vet.DAL.Cita", "Cita")
                        .WithMany("CitaMedicamentos")
                        .HasForeignKey("IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vet.DAL.Medicamento", "Medicamento")
                        .WithMany("CitaMedicamentos")
                        .HasForeignKey("IdMedicamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("Vet.DAL.Mascota", b =>
                {
                    b.HasOne("Vet.DAL.ApplicationUser", "Dueno")
                        .WithMany()
                        .HasForeignKey("DuenoId");

                    b.HasOne("Vet.DAL.RazaMascota", "RazaMascota")
                        .WithMany("Mascotas")
                        .HasForeignKey("IdRazaMascota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vet.DAL.ApplicationUser", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId");

                    b.Navigation("Dueno");

                    b.Navigation("RazaMascota");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("Vet.DAL.PadecimientoMascota", b =>
                {
                    b.HasOne("Vet.DAL.Mascota", "Mascota")
                        .WithMany("PadecimientoMascotas")
                        .HasForeignKey("IdMascota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vet.DAL.Padecimiento", "Padecimiento")
                        .WithMany("PadecimientoMascotas")
                        .HasForeignKey("IdPadecimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mascota");

                    b.Navigation("Padecimiento");
                });

            modelBuilder.Entity("Vet.DAL.RazaMascota", b =>
                {
                    b.HasOne("Vet.DAL.TipoMascota", "TipoMascota")
                        .WithMany("RazaMascotas")
                        .HasForeignKey("IdTipoMascota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoMascota");
                });

            modelBuilder.Entity("Vet.DAL.VacunaMascota", b =>
                {
                    b.HasOne("Vet.DAL.Mascota", "Mascota")
                        .WithMany("VacunaMascotas")
                        .HasForeignKey("IdMascota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vet.DAL.Vacuna", "Vacuna")
                        .WithMany("VacunaMascotas")
                        .HasForeignKey("IdVacuna")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mascota");

                    b.Navigation("Vacuna");
                });

            modelBuilder.Entity("Vet.DAL.Cita", b =>
                {
                    b.Navigation("CitaMedicamentos");
                });

            modelBuilder.Entity("Vet.DAL.Mascota", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("PadecimientoMascotas");

                    b.Navigation("VacunaMascotas");
                });

            modelBuilder.Entity("Vet.DAL.Medicamento", b =>
                {
                    b.Navigation("CitaMedicamentos");
                });

            modelBuilder.Entity("Vet.DAL.Padecimiento", b =>
                {
                    b.Navigation("PadecimientoMascotas");
                });

            modelBuilder.Entity("Vet.DAL.RazaMascota", b =>
                {
                    b.Navigation("Mascotas");
                });

            modelBuilder.Entity("Vet.DAL.TipoMascota", b =>
                {
                    b.Navigation("RazaMascotas");
                });

            modelBuilder.Entity("Vet.DAL.Vacuna", b =>
                {
                    b.Navigation("VacunaMascotas");
                });
#pragma warning restore 612, 618
        }
    }
}
